import Head from 'next/head'
import Navbar from "../components/Navbar";

export default function insurance ()  {
  return <>
       <Head>
        <title>Insurance</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <h1>Insurance</h1>
  </>;
};
